# Generated by Django 3.1.7 on 2023-12-15 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Tarjeta', '0001_initial'),
        ('Movimiento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimiento',
            name='tarjetaDestino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarjetaDestino', to='Tarjeta.tarjeta'),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='tarjetaOrigen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarjetaOrigen', to='Tarjeta.tarjeta'),
        ),
    ]
